// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListEntries(arg1) {
  return window['go']['main']['App']['ListEntries'](arg1);
}

export function MovePath(arg1, arg2) {
  return window['go']['main']['App']['MovePath'](arg1, arg2);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function PickProjectFolder(arg1) {
  return window['go']['main']['App']['PickProjectFolder'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
