// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSnippet(arg1, arg2) {
  return window['go']['main']['App']['AddSnippet'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function GetProcessStats() {
  return window['go']['main']['App']['GetProcessStats']();
}

export function ListEntries(arg1) {
  return window['go']['main']['App']['ListEntries'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function PickProjectFolder(arg1) {
  return window['go']['main']['App']['PickProjectFolder'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFrontmatter(arg1) {
  return window['go']['main']['App']['ReadFrontmatter'](arg1);
}

export function RemoveSnippet(arg1, arg2) {
  return window['go']['main']['App']['RemoveSnippet'](arg1, arg2);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function UpdateSnippet(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSnippet'](arg1, arg2, arg3);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteFrontmatter(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteFrontmatter'](arg1, arg2, arg3);
}
