// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateProject(arg1:string):Promise<string>;

export function DeletePath(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListEntries(arg1:string):Promise<Array<internal.Entry>>;

export function MovePath(arg1:string,arg2:string):Promise<void>;

export function OpenProject(arg1:string):Promise<string>;

export function PickProjectFolder(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RenamePath(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
