// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {internal} from '../models';

export function AddSnippet(arg1:string,arg2:string):Promise<void>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DeletePath(arg1:string):Promise<void>;

export function GetProcessStats():Promise<main.ProcessStats>;

export function ListEntries(arg1:string):Promise<Array<internal.Entry>>;

export function OpenProject(arg1:string):Promise<string>;

export function PickProjectFolder(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFrontmatter(arg1:string):Promise<internal.FrontmatterWithBody>;

export function RemoveSnippet(arg1:string,arg2:number):Promise<void>;

export function RenamePath(arg1:string,arg2:string):Promise<void>;

export function UpdateSnippet(arg1:string,arg2:number,arg3:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteFrontmatter(arg1:string,arg2:internal.FrontmatterData,arg3:string):Promise<void>;
